
services:
  backend:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000" # Expose backend directly since Nginx is removed
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DEBUG=False # Set to False for production
      - POSTGRES_DB=pharmacy_db
      - POSTGRES_USER=pharmacy_user
      - POSTGRES_PASSWORD=pharmacy_password
      - POSTGRES_HOST=db
      - CORS_ALLOWED_ORIGINS=["http://localhost:3000", "http://localhost:3001", "http://backend:8000", "http://localhost:8000"]
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  e-commerce:
    build:
      context: ./e-commerce
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend


  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pharmacy_db
      - POSTGRES_USER=pharmacy_user
      - POSTGRES_PASSWORD=pharmacy_password

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
